name: tomoyomu
description: A Flutter Clean Architecture project with Provider

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  http: ^1.5.0
  lottie: ^3.3.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/splash.json
    - assets/images/logo-TomoYomu.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-TomoYomu.png"

  adaptive_icon_background: "#2B2D42"
  adaptive_icon_foreground: "assets/images/logo-TomoYomu.png"

  remove_alpha_ios: true
